version: "3.7"

x-mongo-service:
  &mongo-service
  image: ${MONGO_IMAGE:-mongo:4.1-bionic}
  environment:
    MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo-root-username
    MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-password
  secrets:
    - mongo-root-username
    - mongo-root-password
    - source: mongo-key
      target: mongod.key
      uid: "999"
      gid: "999"
      mode: 0400
  command: mongod --replSet sample-replica-set --keyFile /run/secrets/mongod.key

services:
  mongo-00:
    <<: *mongo-service
    volumes:
      - mongo_00_data:/data/db

  mongo-01:
    <<: *mongo-service
    volumes:
      - mongo_01_data:/data/db

  mongo-02:
    <<: *mongo-service
    volumes:
      - mongo_02_data:/data/db

networks:
  default:
    attachable: true
    name: ${MONGO_NETWORK_NAME:-mongo-replica-set}

secrets:
  mongo-root-username:
    external: true
    name: ${MONGO_ROOT_USERNAME_SECRET:-mongo-root-username-v1}
  mongo-root-password:
    external: true
    name: ${MONGO_ROOT_PASSWORD_SECRET:-mongo-root-password-v1}
  mongo-key:
    external: true
    name: ${MONGO_KEY_SECRET:-mongo-key-v1}

volumes:
  mongo_00_data:
  mongo_01_data:
  mongo_02_data:
