version: "3.7"

services:
  mongo:
    image: ${MONGO_IMAGE:-mongo:4.1-bionic}
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo-root-username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-password
    secrets:
      - mongo-root-username
      - mongo-root-password
    volumes:
      - mongo_data:/data/db

networks:
  default:
    attachable: true
    name: ${MONGO_NETWORK_NAME:-mongo-secrets}

secrets:
  mongo-root-username:
    external: true
    name: ${MONGO_ROOT_USERNAME_SECRET:-mongo-root-username-v1}
  mongo-root-password:
    external: true
    name: ${MONGO_ROOT_PASSWORD_SECRET:-mongo-root-password-v1}

volumes:
  mongo_data:
